import { getDbClient, runQuery } from "./dal";


async function initDbSchema(): Promise<void> {

    const ddl = `
    BEGIN;

    CREATE TABLE IF NOT EXISTS "user" (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        firstName TEXT NOT NULL,
        lastName TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        passwordHash TEXT NOT NULL,
        isAdmin BOOLEAN NOT NULL DEFAULT FALSE
    );

    CREATE TABLE IF NOT EXISTS vacation (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        destination TEXT NOT NULL,
        description TEXT NOT NULL,
        startDate TIMESTAMPTZ NOT NULL,
        endDate TIMESTAMPTZ NOT NULL,
        price NUMERIC(12,2) NOT NULL CHECK (price > 0),
        imageFileName TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS follower (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        userId BIGINT NOT NULL,
        vacationId BIGINT NOT NULL,

        UNIQUE(userId, vacationId),

        CONSTRAINT fk_follower_user FOREIGN KEY (userId) REFERENCES "user"(id) ON DELETE CASCADE,
        CONSTRAINT fk_follower_vacation FOREIGN KEY (vacationId) REFERENCES vacation(id) ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_user_email             ON "user"(email);

    CREATE INDEX IF NOT EXISTS idx_follower_userId        ON follower(userId);
    CREATE INDEX IF NOT EXISTS idx_follower_vacationId    ON follower(vacationId);

    CREATE INDEX IF NOT EXISTS idx_vacation_startDate     ON vacation(startDate);
    CREATE INDEX IF NOT EXISTS idx_vacation_start_end     ON vacation(startDate, endDate);

    COMMIT;
  `;

    await runQuery(ddl, [], undefined);
}

async function generateSampleData(): Promise<void> {

    const dbClient = await getDbClient();
    try {
        runQuery("BEGIN;", [], dbClient);

        // --- user ---

        // runQuery("INSERT INTO user (firstName, lastName, email, passwordHash, isAdmin) VALUES ('David', 'Levi', 'davidlevi@example.com', 'password123', 0)");
        // runQuery("INSERT INTO user (firstName, lastName, email, passwordHash, isAdmin) VALUES ('Noa', 'tzur', 'noaTzur@example.com', '12345678', 0)");
        // runQuery("INSERT INTO user (firstName, lastName, email, passwordHash, isAdmin) VALUES ('Itay', 'Azoulay', 'itayAzoulay@example.com', '1234abcd', 1)");
        // runQuery("INSERT INTO user (firstName, lastName, email, passwordHash, isAdmin) VALUES ('Tamer', 'Cohen', 'tamerCohen@example.com', 'hello123', 1)");

        // --- vacations ---

        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Paris', 'Romantic city with Eiffel Tower', '2025-12-01', '2025-12-10', 1200.00, 'paris.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Rome', 'Historic sites and delicious food', '2025-11-15', '2025-11-22', 980.00, 'rome.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('New York', 'City that never sleeps', '2025-10-25', '2025-11-05', 1500.00, 'newyork.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Tokyo', 'Blend of tradition and technology', '2025-12-05', '2025-12-15', 1800.00, 'tokyo.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Barcelona', 'Sunny beaches and Gaudi architecture', '2025-10-20', '2025-10-28', 1100.00, 'barcelona.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('London', 'Museums, parks, and shopping', '2025-11-10', '2025-11-18', 1300.00, 'london.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Bangkok', 'Street food and vibrant culture', '2025-12-12', '2025-12-22', 900.00, 'bangkok.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Sydney', 'Opera House and beaches', '2025-12-20', '2025-12-30', 2000.00, 'sydney.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Amsterdam', 'Canals and bike rides', '2025-11-01', '2025-11-09', 1050.00, 'amsterdam.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Dubai', 'Luxury shopping and desert safaris', '2025-12-08', '2025-12-14', 1700.00, 'dubai.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Istanbul', 'Where East meets West', '2025-11-20', '2025-11-27', 950.00, 'istanbul.jpg')");
        runQuery("INSERT INTO vacation (destination, description, startDate, endDate, price, imageFileName) VALUES ('Cape Town', 'Mountains, beaches, and wine', '2025-12-18', '2025-12-28', 1600.00, 'capetown.jpg')");

        // --- follower ---

        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (1, 2)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (1, 3)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (1, 4)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (2, 1)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (2, 4)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (2, 2)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (3, 5)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (3, 1)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (3, 6)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (4, 1)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (4, 2)");
        // runQuery("INSERT INTO follower (userId, vacationId) VALUES (4, 3)");

        runQuery("COMMIT;", [], dbClient);
    } catch (error) {
        runQuery("ROLLBACK", [], dbClient);
        throw error;
    } finally {
        dbClient.release();
    }
}

initDbSchema();
// generateSampleData();